<a href="https://colab.research.google.com/github/orangNLP/Algorithm_practice/blob/main/pytorch/pytorch_nn_Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Run All Codes**

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

##**Linear Regression**

In [2]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [3]:
x_train

tensor([[1.],
        [2.],
        [3.]])

In [4]:
W = torch.zeros(1, requires_grad =  True)
W

tensor([0.], requires_grad=True)

In [5]:
b = torch.zeros(1, requires_grad = True)
b

tensor([0.], requires_grad=True)

In [6]:
hypothesis = torch.matmul(x_train, W) + b
hypothesis

tensor([0., 0., 0.], grad_fn=<AddBackward0>)

In [7]:
cost = torch.mean((hypothesis - y_train)**2)
cost

tensor(18.6667, grad_fn=<MeanBackward0>)

In [8]:
optimizer = optim.SGD([W,b], lr = 0.01)

In [9]:
optimizer.zero_grad()
cost.backward() #미분
optimizer.step()

In [10]:
cost.backward

<bound method Tensor.backward of tensor(18.6667, grad_fn=<MeanBackward0>)>

In [11]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
W = torch.zeros(1, requires_grad =  True)
b = torch.zeros(1, requires_grad = True)
epochs = 2000
for i in range(epochs+1):
  hypothesis = x_train.matmul(W) + b
  cost = torch.mean((hypothesis - y_train)**2)
  optimizer = optim.SGD([W,b], lr = 0.01)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if i % 100 == 0:
    print('epochs:', i, f'W: {W[0]}, b: {b[0]}, cost: {cost}')

epochs: 0 W: 0.1599999964237213, b: 0.07999999821186066, cost: 18.66666603088379
epochs: 100 W: 1.1561442613601685, b: 1.3717844486236572, cost: 3.662370443344116
epochs: 200 W: 0.9088429808616638, b: 1.9339863061904907, cost: 3.281951665878296
epochs: 300 W: 0.7144335508346558, b: 2.375924587249756, cost: 3.0468757152557373
epochs: 400 W: 0.5616096258163452, b: 2.7233293056488037, cost: 2.9016122817993164
epochs: 500 W: 0.44147637486457825, b: 2.996420383453369, cost: 2.8118488788604736
epochs: 600 W: 0.3470405638217926, b: 3.2110955715179443, cost: 2.756380558013916
epochs: 700 W: 0.27280542254447937, b: 3.3798491954803467, cost: 2.72210431098938
epochs: 800 W: 0.21445001661777496, b: 3.512504816055298, cost: 2.7009239196777344
epochs: 900 W: 0.1685771942138672, b: 3.6167845726013184, cost: 2.687835454940796
epochs: 1000 W: 0.13251720368862152, b: 3.6987571716308594, cost: 2.6797475814819336
epochs: 1100 W: 0.10417044907808304, b: 3.7631959915161133, cost: 2.6747500896453857
epochs: 

##**Autograd**

In [12]:
w = torch.tensor(2.0, requires_grad=True)


In [13]:
y = w**2
z = 2*y + 5
z.backward()
print(w.grad)

tensor(8.)


In [14]:
x = torch.FloatTensor([[2,3,4,7,3], [3,2,6,2,1]])
w = torch.zeros((5,2), requires_grad = True)
b = torch.tensor(5.0, requires_grad = True)
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


##**nn.Module**

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [16]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [17]:
model = nn.Linear(1,1) #nn.Linear(input_dim. output_dim)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.8700]], requires_grad=True), Parameter containing:
tensor([-0.8926], requires_grad=True)]


In [18]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [19]:
epochs = 2000
for i in range(epochs+1):
  Hx = model(x_train)
  cost =  F.mse_loss(Hx, y_train) #MeanSquaredError. Hx, y
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

In [20]:
type(list(model.parameters())[0])

torch.nn.parameter.Parameter

In [21]:
model(torch.FloatTensor([5]))

tensor([9.9970], grad_fn=<AddBackward0>)

In [22]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [23]:
Linear = nn.Linear(3,1)
list(Linear.parameters())

[Parameter containing:
 tensor([[-0.3112,  0.5575,  0.5478]], requires_grad=True),
 Parameter containing:
 tensor([-0.3518], requires_grad=True)]

In [24]:
Linear_optimizer = optim.SGD(Linear.parameters(), lr = 1e-5)

In [25]:
epochs = 2000
for i in range(epochs+1):
  Hx = Linear(x_train)
  loss_function = F.mse_loss(Hx,y_train)
  Linear_optimizer.zero_grad()
  loss_function.backward()
  Linear_optimizer.step()
print(list(Linear.parameters()))

[Parameter containing:
tensor([[0.3336, 0.6976, 0.9801]], requires_grad=True), Parameter containing:
tensor([-0.3410], requires_grad=True)]


In [26]:
Linear(torch.FloatTensor([70, 60, 50]))

tensor([113.8705], grad_fn=<AddBackward0>)

In [27]:
class MultiLayerLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1) 
  
  def forward(self, x):
    return self.linear(x)
config = {'input_dim': 3, 'output_dim':1} 
Model = MultiLayerLinearRegression()
optimizer = optim.SGD(Model.parameters(), lr = 1e-5)
for i in range(epochs+1):
  Hx = Model(x_train)
  loss_function = F.mse_loss(Hx, y_train)
  optimizer.zero_grad()
  loss_function.backward()
  optimizer.step()

In [28]:
Model(torch.FloatTensor([1,21,50]))

tensor([66.1544], grad_fn=<AddBackward0>)